<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Designer.ico</ApplicationIcon>
    <IsAotCompatible>true</IsAotCompatible>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <PublishAot>true</PublishAot>
    <Platforms>x64</Platforms>
    <AssemblyName>PaletteDesigner</AssemblyName>
    <Title>Palette Designer</Title>
    <Company>Lyt Games</Company>
    <Product>Palette Designer</Product>
    <PackageIcon>Designer.png</PackageIcon>
    <Description>An interactive tool to generate beautiful color palettes and themes, exporting projects to Adobe ASE, XAML, AXAML and JSON for use in various applications</Description>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Designer.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\Lyt.Avalonia.PaletteDesigner\Assets\Images\Designer.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
          <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
          <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Nullable.Extended.Analyzer" Version="1.16.6891">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
      <PackageReference Include="SkiaSharp" Version="4.152.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Lyt.Avalonia.PaletteDesigner\Lyt.Avalonia.PaletteDesigner.csproj" />
    </ItemGroup>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
      <Exec Command="start /WAIT ..\Tools\prebuild.bat&#xD;&#xA;" />
    </Target>
</Project>
