// Referenced assemblies 
#r "System"
#r "System.Collections"

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

$@"; Paint.NET Palette File
; Lines that start with a semicolon are comments
; Colors are written as 8-digit hexadecimal numbers: aarrggbb
; {ImagePaletteSource} - Autogenerated by Palette Designer: {DateTime.Now} 
;	
{	string.Join
		(
			Environment.NewLine,
			Colors.Select(entry => entry)
		)}
;
"